### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by Garthmj** [MechaChocobo/NotesManager#1]
I don't see where you show how to access media listed on SharpSpring (SS). Nor did I see where you can upload a new media item to SS.

**Comment by MechaChocobo** [comment]
Thank you for your comment. This project was created as a concept, and is not meant for actual use. It is not maintained by, supported by, or affiliated with SharpSpring.

**Comment by MechaChocobo** [comment]
Renamed the project to avoid future confusion. Sorry for the trouble.
